In [ ]:
## sometime without uninstalling faiss-gpu "import faiss" doesn't work ## 
!apt install libomp-dev
!python -m pip uninstall faiss-gpu
!python -m pip install --upgrade faiss faiss-gpu
import faiss

In [ ]:
!apt install libomp-dev
!python -m pip install --upgrade faiss faiss-gpu
import faiss

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libomp-dev is already the newest version (5.0.1-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.


In [ ]:
import pandas as pd
import numpy as np
embeddings = pd.read_csv("/content/drive/MyDrive/emotion_flow_thesis/nrclexicon/embeddings.csv")
display(embeddings)
embeddings =  np.array(embeddings)
embeddings

0         1         2  ...       509       510       511
0     0.109317  0.001561 -0.038709  ...  0.083619 -0.030489  0.052017
1     0.106047 -0.027544  0.021171  ...  0.069374 -0.003556  0.071969
2     0.102450  0.026601 -0.028719  ...  0.067079 -0.025844  0.062328
3     0.104426 -0.017742 -0.028025  ...  0.072193 -0.032594  0.059819
4     0.100910 -0.023130  0.009070  ...  0.054959 -0.000085  0.067003
...        ...       ...       ...  ...       ...       ...       ...
9894  0.121820 -0.077349 -0.043410  ...  0.033871 -0.015184  0.024248
9895  0.090154 -0.048566 -0.012236  ...  0.037675  0.024719  0.065148
9896  0.122708  0.009699 -0.010126  ...  0.039268 -0.007500  0.081011
9897  0.107988 -0.007806  0.049510  ...  0.016026 -0.005857  0.019257
9898  0.138728 -0.014191  0.000289  ...  0.073778 -0.023939  0.098280

[9899 rows x 512 columns]

array([[ 0.10931715,  0.00156129, -0.03870945, ...,  0.08361889,
        -0.03048883,  0.05201654],
       [ 0.10604725, -0.02754442,  0.02117088, ...,  0.0693742 ,
        -0.00355639,  0.07196925],
       [ 0.10245   ,  0.02660078, -0.02871861, ...,  0.06707921,
        -0.02584359,  0.06232785],
       ...,
       [ 0.12270841,  0.00969893, -0.01012613, ...,  0.03926771,
        -0.00750015,  0.08101127],
       [ 0.10798796, -0.00780552,  0.04950984, ...,  0.01602573,
        -0.00585708,  0.01925723],
       [ 0.13872795, -0.01419058,  0.00028933, ...,  0.0737779 ,
        -0.02393907,  0.09827964]])

In [ ]:
## conver array to C-continuous for Faiss ##
embeddings = embeddings.copy(order='C')
display(embeddings.flags)

## convert numpy array to float32 for Faiss ##
embeddings.dtype
embeddings = np.float32(embeddings)
embeddings.dtype



In [ ]:
d = embeddings.shape[1]
index = faiss.IndexFlatL2(d)  
index.add(embeddings)

###### load multilingual model

In [ ]:
!pip install tensorflow-text
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
from scipy import spatial


In [ ]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3"
multilingual_model = hub.load(module_url)

In [ ]:
test_input = "Ausbildung"
test_embedding = multilingual_model(test_input)
test_embedding = np.array(test_embedding)

In [ ]:
D, I = index.search(test_embedding, 1)

In [ ]:
D

array([[0.6864945]], dtype=float32)

In [ ]:
I

array([[8797]])